datahub:
  image: ssh_test
  links:
    - db:mysql
  ports:
    - 8081:8080

db:
  image: mysql:5.5.utf-8
  environment:
    MYSQL_ROOT_PASSWORD: mysqladmin
    MYSQL_USER: datahub
    MYSQL_PASSWORD: datahub
    MYSQL_DATABASE: datahub
  volumes:
    - /home/rfm/mysql_data:/var/lib/mysql
  ports:
    - 3306:3306
